### News Crawling

In [48]:
# 네이버 뉴스 여성 살해 검거 검색 >> 2022/1월

# 라이브러리
import requests
from bs4 import BeautifulSoup 
import urllib
import urllib.request as rq
import pandas as pd
import requests
import openpyxl
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
import re
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager


# 웹드라이버 설정
options = webdriver.ChromeOptions()
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option("useAutomationExtension", False)



start=1
news_df = pd.DataFrame()

while True:
    try:
        url = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query=%EC%97%AC%EC%84%B1%20%EC%82%B4%ED%95%B4%20%EA%B2%80%EA%B1%B0&sort=0&photo=0&field=0&pd=3&ds=2022.01.01&de=2022.01.31&cluster_rank=53&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20220101to20220131,a:all&start=1'.format(start)

        # url = https://search.naver.com/search.naver?where=news&sm=tab_jum&query='+keyword+'&start='+str(page_num)
        #url = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query='+keyword+'&sort=1&photo=0&field=0&pd=3&ds='+date_s+'&de='+date_e+'&start='+str(page)
        headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'}


        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'lxml')

        news_title = [title['title'] for title in soup.find_all('a', attrs={'class':'news_tit'})]
        news_url = [url['href'] for url in soup.find_all('a',attrs={'class':'news_tit'})]
        dates = [date.get_text() for date in soup.find_all('span', attrs={'class':'info'})]
       
        news_date = []
        for date in dates:
            if re.search(r'\d+.\d+.\d+',date) !=None:
                news_date.append(date)

        new_df = set(news_title)        

        df = pd.DataFrame({'date':news_date,'title':news_title, 'url':news_url})
        news_df  = pd.concat([news_df, df], ignore_index=True)
        start += 10

    except:
        print(start)
        break

3431

In [49]:
news_df_1 = news_df.copy()
news_df_1.to_csv('news_df_1.csv')
news_df_1 = pd.read_csv('news_df_1.csv')
news_df_1

,Unnamed: 0,date,title,url
0,0,2022.01.29.,'악의 마음' 김남길X진선규 어쩌나..연쇄살인범 검거 난항 [★밤TView],http://star.mt.co.kr/stview.php?no=20220129214...
1,1,2022.01.27.,차 타는 순간 흉기로 여성 위협…금품 빼앗은 강도 검거,http://www.edaily.co.kr/news/newspath.asp?news...
2,2,2022.01.25.,차량서 50대 여성 흉기에 찔려 숨진 채 발견…남편 살해 추정,https://www.news1.kr/articles/?4565509
3,3,2022.01.19.,이별 통보한 전 여친 살해한 27세 조현진 신상공개,http://news.kmib.co.kr/article/view.asp?arcid=...
4,4,2022.01.29.,'악의 마음' 부유층 연쇄살인 발생에 유영철 재조명 '10개월 간 20명 살해',http://www.gukjenews.com/news/articleView.html...
...,...,...,...,...
3425,3425,2022.01.28.,"경찰, 이별 통보에 '흉기 사진' 보낸 40대 불법 체류자 검거",https://www.ytn.co.kr/_ln/0103_202201281526301793
3426,3426,2022.01.13.,이별 통보한 여성에게 흉기 휘둘러 살해한 20대 검거,http://yna.kr/AKR20220113024800063?did=1195m
3427,3427,2022.01.10.,‘신변보호’ 피해자 주소 살해범에 넘긴 정보원은 구청 공무원,https://www.seoul.co.kr/news/newsView.php?id=2...
3428,3428,2022.01.13.,천안 원룸서 여자친구 살해 혐의 20대 남성 검거,https://news.kbs.co.kr/news/view.do?ncd=537214...
3429,3429,2022.01.13.,"""헤어지자""‥전 여자친구 살해한 20대 검거",https://imnews.imbc.com/replay/2022/nwdesk/art...

In [53]:
#인덱스 칼럼 생성되었을 때 제거
#news_df_1 = news_df_1.drop(['Unnamed: 0'], axis=1, inplace=True)

In [33]:
# 네이버 뉴스 여성 살해 검거 검색 >> 2022/2월

# 라이브러리
import requests
from bs4 import BeautifulSoup 
import urllib
import urllib.request as rq
import pandas as pd
import requests
import openpyxl
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
import re
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager


# 웹드라이버 설정
options = webdriver.ChromeOptions()
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option("useAutomationExtension", False)



start=1
news_df = pd.DataFrame()

while True:
    try:
        url = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query=%EC%97%AC%EC%84%B1%20%EC%82%B4%ED%95%B4%20%EA%B2%80%EA%B1%B0&sort=0&photo=0&field=0&pd=3&ds=2022.02.01&de=2022.02.28&cluster_rank=82&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20220201to20220228,a:all&start=1'.format(start)
        headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'}

        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'lxml')

        news_title = [title['title'] for title in soup.find_all('a', attrs={'class':'news_tit'})]
        news_url = [url['href'] for url in soup.find_all('a',attrs={'class':'news_tit'})]
        dates = [date.get_text() for date in soup.find_all('span', attrs={'class':'info'})]
       
        news_date = []
        for date in dates:
            if re.search(r'\d+.\d+.\d+',date) !=None:
                news_date.append(date)

        new_df = set(news_title)        

        df = pd.DataFrame({'date':news_date,'title':news_title, 'url':news_url})
        news_df  = pd.concat([news_df, df], ignore_index=True)
        start += 10

    except:
        print(start)
        break

1961

In [34]:
news_df_2 = news_df.copy()
news_df_2.to_csv('news_df_2.csv')
news_df_2 = pd.read_csv('news_df_2.csv')
news_df_2

,Unnamed: 0,date,title,url
0,0,2022.02.26.,"'악의 마음', 부유층 연쇄살인범 검거→도주..'충격 엔딩' [종합]",http://star.mt.co.kr/stview.php?no=20220226065...
1,1,2022.02.26.,'동거녀 살해·평소 알고 지낸 여성 흉기' 찌른 50대 중국인 검거,http://www.kyeongin.com/main/view.php?key=2022...
2,2,2022.02.26.,"""찌질한 살인자일 뿐""...'악의 마음' 김남길, 연쇄살인범 검거 [종합]",https://www.xportsnews.com/article/1542193
3,3,2022.02.23.,안양서 식당 주인 살해 뒤 대전까지 도주…40대 남성 체포,https://news.kbs.co.kr/news/view.do?ncd=540243...
4,4,2022.02.25.,"김제에서 50대 여성 숨진 채 발견.. ""살해 용의자 검거""",http://www.jmbc.co.kr/news/view/22009
...,...,...,...,...
1955,1955,2022.02.15.,"서울서 또 신변보호 여성 피살…경찰, 용의자 추적 중",https://www.news1.kr/articles/?4584803
1956,1956,2022.02.15.,[단독]또 신변보호 여성 사망···스마트워치로 경찰에 알렸지만 못 막았다,https://www.khan.co.kr/national/national-gener...
1957,1957,2022.02.15.,[속보] 구로 신변보호 대상 여성 살해 용의자 숨진채 발견,http://news.mk.co.kr/newsRead.php?no=140990&ye...
1958,1958,2022.02.11.,"""나를 무시해 홧김에""…60대 부인 살해한 남편 검거(종합)",http://www.newsis.com/view/?id=NISX20220211_00...
1959,1959,2022.02.24.,안양서 70대 업주 살해 후 도주한 40대男 사흘 만에 검거,http://www.hg-times.com/news/articleView.html?...

In [8]:
# 네이버 뉴스 여성 살해 검거 검색 >> 2022/3월

# 라이브러리
import requests
from bs4 import BeautifulSoup 
import urllib
import urllib.request as rq
import pandas as pd
import requests
import openpyxl
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
import re
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager


# 웹드라이버 설정
options = webdriver.ChromeOptions()
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option("useAutomationExtension", False)



start=1
news_df = pd.DataFrame()

while True:
    try:
        url = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query=%EC%97%AC%EC%84%B1%20%EC%82%B4%ED%95%B4%20%EA%B2%80%EA%B1%B0&sort=0&photo=0&field=0&pd=3&ds=2022.03.01&de=2022.03.31&cluster_rank=25&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20220301to20220331,a:all&start=1'.format(start)

        # url = https://search.naver.com/search.naver?where=news&sm=tab_jum&query='+keyword+'&start='+str(page_num)
        #url = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query='+keyword+'&sort=1&photo=0&field=0&pd=3&ds='+date_s+'&de='+date_e+'&start='+str(page)
        headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'}


        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'lxml')

        news_title = [title['title'] for title in soup.find_all('a', attrs={'class':'news_tit'})]
        news_url = [url['href'] for url in soup.find_all('a',attrs={'class':'news_tit'})]
        dates = [date.get_text() for date in soup.find_all('span', attrs={'class':'info'})]
       
        news_date = []
        for date in dates:
            if re.search(r'\d+.\d+.\d+',date) !=None:
                news_date.append(date)

        new_df = set(news_title)        

        df = pd.DataFrame({'date':news_date,'title':news_title, 'url':news_url})
        news_df  = pd.concat([news_df, df], ignore_index=True)
        start += 10

    except:
        print(start)
        break

3311

In [9]:
news_df_3 = news_df.copy()
news_df_3.to_csv('news_df_3.csv')
news_df_3 = pd.read_csv('news_df_3.csv')
news_df_3

,Unnamed: 0,date,title,url
0,0,2022.03.30.,수영 못하는 남편 다이빙시켜 살해…아내·공범 공개수배,http://news.kmib.co.kr/article/view.asp?arcid=...
1,1,2022.03.30.,‘가평 계곡 살인’ 30대 여성·공범 공개수배,http://www.segye.com/content/html/2022/03/30/2...
2,2,2022.03.24.,'신변보호 여성 가족살해' 이석준에 정보 판 30대 징역 2년 구형,http://news.tf.co.kr/read/life/1926550.htm
3,3,2022.03.25.,이웃 성폭행하고 살해…인면수심 40대 징역 30년,https://www.nocutnews.co.kr/news/5729202
4,4,2022.03.25.,이웃집 60대 여성 성폭행·살해한 40대 남성 징역 30년,https://biz.chosun.com/topics/law_firm/2022/03...
...,...,...,...,...
3305,3305,2022.03.28.,"“스토킹 살해범 김병찬, 사형 처해달라”…재판부 향한 유족들의 절규",http://www.segye.com/content/html/2022/03/28/2...
3306,3306,2022.03.13.,호신용품으로 동거남 때려 살해한 30대 여성 검거,http://yna.kr/AKR20220313016000064?did=1195m
3307,3307,2022.03.17.,"""집수리 왜 안 해줘""..집주인 살해한 60대, 긴급체포",http://www.fnnews.com/news/202203171031508306
3308,3308,2022.03.26.,‘돈 빌려달라’ 거절한 이웃집 여성 성폭행 후 살해한 40대…피해자인양 휴대폰 안부...,http://www.segye.com/content/html/2022/03/25/2...
3309,3309,2022.03.16.,"“한국의 여성운동, ‘피해망상 페미니즘’으로 변질됐다”",https://www.chosun.com/national/national_gener...

In [10]:
# 네이버 뉴스 여성 살해 검거 검색 >> 2022/4월

# 라이브러리
import requests
from bs4 import BeautifulSoup 
import urllib
import urllib.request as rq
import pandas as pd
import requests
import openpyxl
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
import re
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager


# 웹드라이버 설정
options = webdriver.ChromeOptions()
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option("useAutomationExtension", False)



start=1
news_df = pd.DataFrame()

while True:
    try:
        url = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query=%EC%97%AC%EC%84%B1%20%EC%82%B4%ED%95%B4%20%EA%B2%80%EA%B1%B0&sort=0&photo=0&field=0&pd=3&ds=2022.04.01&de=2022.04.30&cluster_rank=44&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20220401to20220430,a:all&start=1'.format(start)
        headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'}


        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'lxml')

        news_title = [title['title'] for title in soup.find_all('a', attrs={'class':'news_tit'})]
        news_url = [url['href'] for url in soup.find_all('a',attrs={'class':'news_tit'})]
        dates = [date.get_text() for date in soup.find_all('span', attrs={'class':'info'})]
       
        news_date = []
        for date in dates:
            if re.search(r'\d+.\d+.\d+',date) !=None:
                news_date.append(date)

        new_df = set(news_title)        

        df = pd.DataFrame({'date':news_date,'title':news_title, 'url':news_url})
        news_df  = pd.concat([news_df, df], ignore_index=True)
        start += 10

    except:
        print(start)
        break

3301

In [11]:
news_df_4 = news_df.copy()
news_df_4.to_csv('news_df_4.csv')
news_df_4 = pd.read_csv('news_df_4.csv')
news_df_4

,Unnamed: 0,date,title,url
0,0,2022.04.25.,강서구 60대 여성 살해 피의자 검거… “돈 많을 줄 알았다”,http://www.segye.com/content/html/2022/04/25/2...
1,1,2022.04.27.,"""돈 많아 보여서"" 이웃 살해 40대…1시간 구속심사(종합)",http://www.newsis.com/view/?id=NISX20220427_00...
2,2,2022.04.25.,강서구 아파트 60대 여성 살해 40대 남성 검거…“돈 필요해서”,https://www.hani.co.kr/arti/society/society_ge...
3,3,2022.04.26.,"경찰, 강서구 60대 여성 살해 40대 남성 구속영장 신청",http://www.fnnews.com/news/202204261120167268
4,4,2022.04.27.,"'강서구 이웃 여성 살인' 피의자 구속…""도망 염려""",https://www.nocutnews.co.kr/news/5747828
...,...,...,...,...
3295,3295,2022.04.27.,강서 60대 여성 살해 40대 이웃 남성 구속,https://www.news1.kr/articles/?4663183
3296,3296,2022.04.24.,"경찰, 서울 강서구 60대女 살해 용의자 40대男 추적",https://www.donga.com/news/article/all/2022042...
3297,3297,2022.04.25.,등촌동 여성 살해 용의자 검거…“단 몇 만원 때문에”?,https://news.kbs.co.kr/news/view.do?ncd=544833...
3298,3298,2022.04.27.,이웃집 60대女 살해 뒤…장롱 서랍 속 2만원 갖고 튄 그놈,https://www.joongang.co.kr/article/25066932
3299,3299,2022.04.25.,[속보] 서울 등촌동 아파트 강도살인 피의자 검거...40대 이웃 남성,https://www.ytn.co.kr/_ln/0103_202204250851476837

In [13]:
# 네이버 뉴스 여성 살해 검거 검색 >> 2022/5월

# 라이브러리
import requests
from bs4 import BeautifulSoup 
import urllib
import urllib.request as rq
import pandas as pd
import requests
import openpyxl
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
import re
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager


# 웹드라이버 설정
options = webdriver.ChromeOptions()
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option("useAutomationExtension", False)



start=1
news_df = pd.DataFrame()

while True:
    try:
        url = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query=%EC%97%AC%EC%84%B1%20%EC%82%B4%ED%95%B4%20%EA%B2%80%EA%B1%B0&sort=0&photo=0&field=0&pd=3&ds=2022.05.01&de=2022.05.31&cluster_rank=41&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20220501to20220531,a:all&start=1'.format(start)
        headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'}


        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'lxml')

        news_title = [title['title'] for title in soup.find_all('a', attrs={'class':'news_tit'})]
        news_url = [url['href'] for url in soup.find_all('a',attrs={'class':'news_tit'})]
        dates = [date.get_text() for date in soup.find_all('span', attrs={'class':'info'})]
       
        news_date = []
        for date in dates:
            if re.search(r'\d+.\d+.\d+',date) !=None:
                news_date.append(date)

        new_df = set(news_title)        

        df = pd.DataFrame({'date':news_date,'title':news_title, 'url':news_url})
        news_df  = pd.concat([news_df, df], ignore_index=True)
        start += 10

    except:
        print(start)
        break

3361

In [14]:
news_df_5 = news_df.copy()
news_df_5.to_csv('news_df_5.csv')
news_df_5 = pd.read_csv('news_df_5.csv')
news_df_5

,Unnamed: 0,date,title,url
0,0,2022.05.27.,전 남편 차로 치어 살해하려 한 여성 검거‥공무집행 방해도,https://imnews.imbc.com/news/2022/society/arti...
1,1,2022.05.24.,중증장애 딸 살해 후 극단 선택 시도한 60대 여성 검거,https://news.sbs.co.kr/news/endPage.do?news_id...
2,2,2022.05.24.,"""30년간 홀로 돌봄""...중증장애 딸 살해한 60대 검거",https://www.ytn.co.kr/_ln/0103_202205241246390721
3,3,2022.05.24.,'뇌병변 장애 앓는 딸' 수면제 먹여 살해한 60대 친모 검거,http://www.newsis.com/view/?id=NISX20220524_00...
4,4,2022.05.26.,"""너무 미안해"" 30년간 뇌병변 딸 돌보다 살해한 엄마 영장 기각",http://www.fnnews.com/news/202205252249229863
...,...,...,...,...
3355,3355,2022.05.23.,인천시 남동구 빌라서 여성 살해한 20대 남성 검거,https://news.kbs.co.kr/news/view.do?ncd=546946...
3356,3356,2022.05.25.,"""같이 살지 못해 미안해""… 뇌병변 딸 살해한 친모, 영장심사",http://moneys.mt.co.kr/news/mwView.php?no=2022...
3357,3357,2022.05.25.,동거남 살해한 혐의 50대 여성 검거… 경찰 “술 마시다 다툰 듯”,http://www.segye.com/content/html/2022/05/25/2...
3358,3358,2022.05.16.,부산 해운대 주택서 50대 여성 살해한 60대 남성 검거(종합),https://www.yna.co.kr/view/AKR2022051600540105...
3359,3359,2022.05.24.,지적장애인 인천·김포서 살해·암매장 2030 남녀 4명 구속기소,https://news.imaeil.com/page/view/202205241931...

In [90]:
# 네이버 뉴스 살해 징역 검색 >> 2022/6월

# 라이브러리
import requests
from bs4 import BeautifulSoup 
import urllib
import urllib.request as rq
import pandas as pd
import requests
import openpyxl
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
import re
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager


# 웹드라이버 설정
options = webdriver.ChromeOptions()
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option("useAutomationExtension", False)


news_df = pd.DataFrame()

while True:
    try:

        url = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query=%EC%82%B4%ED%95%B4%20%EC%A7%95%EC%97%AD&sort=0&photo=0&field=0&pd=3&ds=2022.06.01&de=2022.06.30&cluster_rank=21&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20220601to20220630,a:all&'
        headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'}

       
        
        for i in range(0, 50):
            response = requests.get(url, headers=headers, params = {'start' : 1+10*i})
            soup = BeautifulSoup(response.text, 'lxml')


            news_title = [title['title'] for title in soup.find_all('a', attrs={'class':'news_tit'})]
            news_url = [url['href'] for url in soup.find_all('a',attrs={'class':'news_tit'})]
            dates = [date.get_text() for date in soup.find_all('span', attrs={'class':'info'})]

            news_date = []
            for date in dates:
                if re.search(r'\d+.\d+.\d+',date) !=None:
                    news_date.append(date)

            new_df = set(news_title)        

            df = pd.DataFrame({'date':news_date,'title':news_title, 'url':news_url})
            news_df  = pd.concat([news_df, df], ignore_index=True)
            #start += 10

    except:
        print(num)
        break

50

In [91]:
news_df_6 = news_df.copy()
news_df_6.to_csv('news_df_6.csv')
news_df_6 = pd.read_csv('news_df_6.csv')
news_df_6

,Unnamed: 0,date,title,url
0,0,2022.06.30.,"'자녀 살해한 부모' 처벌 강화법, 국회 발의돼 있지만…",https://news.jtbc.joins.com/article/article.as...
1,1,2022.06.30.,"자녀살해 후 극단선택…법원은 ""동반자살 아닌 살인"" 질타",https://www.yna.co.kr/view/AKR2022063008310000...
2,2,2022.06.30.,"독일 법원, 혐의 부인한 101세 나치 부역자에 '징역 5년' 선고",http://news.mt.co.kr/mtview.php?no=20220630084...
3,3,2022.06.30.,"자녀 동반 비극은 '비속살해'…""자녀 생명은 부모의 것 아냐""",http://www.newsis.com/view/?id=NISX20220630_00...
4,4,2022.06.29.,"‘중년여성·공범 살해’ 권재찬, 1심 사형 불복해 항소… 검찰도 맞항소",https://www.seoul.co.kr/news/newsView.php?id=2...
...,...,...,...,...
1255,1255,2022.06.25.,"‘신변보호 여성 가족 살해’ 이석준·검찰, 1심 무기징역 판결에 항소",https://www.dailian.co.kr/news/view/1126358/?s...
1256,1256,2022.06.16.,스토킹하려 빈 원룸에 몰래 거주…건물주 살해한 40대 무기징역,https://www.seoul.co.kr/news/newsView.php?id=2...
1257,1257,2022.06.15.,'정인이법 첫 적용' 의붓딸 살해 사건 항소 기각…징역 30년,http://www.segye.com/content/html/2022/06/15/2...
1258,1258,2022.06.22.,'댐 건설 반대' 온두라스 환경운동가 살해한 기업인 22년형,https://www.yna.co.kr/view/AKR2022062200330008...
1259,1259,2022.06.22.,"'전 여친 스토킹 살해' 김병찬, 징역 35년 불복해 항소",https://www.ajunews.com/view/20220622172043100

In [93]:
news_df_6.head(30)

,Unnamed: 0,date,title,url
0,0,2022.06.30.,"'자녀 살해한 부모' 처벌 강화법, 국회 발의돼 있지만…",https://news.jtbc.joins.com/article/article.as...
1,1,2022.06.30.,"자녀살해 후 극단선택…법원은 ""동반자살 아닌 살인"" 질타",https://www.yna.co.kr/view/AKR2022063008310000...
2,2,2022.06.30.,"독일 법원, 혐의 부인한 101세 나치 부역자에 '징역 5년' 선고",http://news.mt.co.kr/mtview.php?no=20220630084...
3,3,2022.06.30.,"자녀 동반 비극은 '비속살해'…""자녀 생명은 부모의 것 아냐""",http://www.newsis.com/view/?id=NISX20220630_00...
4,4,2022.06.29.,"‘중년여성·공범 살해’ 권재찬, 1심 사형 불복해 항소… 검찰도 맞항소",https://www.seoul.co.kr/news/newsView.php?id=2...
5,5,2022.06.24.,"법원, '발달장애 딸 살해' 50대 엄마 징역 6년 선고",https://www.ytn.co.kr/_ln/0103_202206241212278154
6,6,2022.06.29.,술마시다 말다툼한 남성 흉기로 살해하려 한 60대 '집유',https://www.news1.kr/articles/?4726191
7,7,2022.06.29.,술에 취해 우발적으로 50대男 살해하려 한 60대男 '집유',http://www.newsis.com/view/?id=NISX20220628_00...
8,8,2022.06.28.,'주점업주 사망 전 성폭행' 중국인 1심 징역 3년에 항소,https://www.yna.co.kr/view/AKR2022062805180006...
9,9,2022.06.28.,“석연찮으나 입증 못했다”... 21살 연상 동거녀 방화 살해 혐의 30대 무죄,https://www.chosun.com/national/incident/2022/...
10,10,2022.06.30.,"獨법원, 102세 나치 교도관에 징역 5년형… “살인시스템 도와”[사람, 세계]",https://www.donga.com/news/article/all/2022063...
11,11,2022.06.29.,"獨, 나치 전범 101세 노인에게 징역 5년 선고",http://www.munhwa.com/news/view.html?no=202206...
12,12,2022.06.28.,반전 스티커 하나로 징역 10년… 러 여가수 “감옥서 성학대 당했다”,https://www.chosun.com/international/internati...
13,13,2022.06.25.,"20개월 의붓딸 성폭행·살해 계부, 무기징역 확정",https://news.imaeil.com/page/view/202206250819...
14,14,2022.06.28.,"""왜 무시해"" 지인 흉기로 찌른 40대 징역 2년6개월",https://www.yna.co.kr/view/AKR2022062809630006...
15,15,2022.06.24.,'아내와 관계 의심' 동창생 살해 20대 항소심도 징역 15년,https://www.yna.co.kr/view/AKR2022062406500006...
16,16,2022.06.28.,'주점업주 사망 전 성폭행' 중국인 1심 징역 3년에 항소,https://www.yna.co.kr/view/AKR2022062805180006...
17,17,2022.06.29.,딸 못 만나게 한 전처 살해미수 50대 실형,https://www.news1.kr/articles/?4726990
18,18,2022.06.21.,‘신변보호 여성 가족 살해’ 이석준에 무기징역…1심 “보복 목적 살해”,https://www.seoul.co.kr/news/newsView.php?id=2...
19,19,2022.06.30.,"[아주 돋보기] 조유나양은 살해당했다…""아이는 부모 소유물 아냐"" 비난",https://www.ajunews.com/view/20220630135600447
20,20,2022.06.22.,동거남 삼단봉 폭행 살해…30대 여성 징역 25년,https://www.yna.co.kr/view/AKR2022062205550006...
21,21,2022.06.24.,'신변보호 여성 가족 살해' 이석준 1심 무기징역에 항소,https://www.hankyung.com/society/article/20220...
22,22,2022.06.24.,"""하루 결근 2천만원 물어내"" '노예 PC방' 업주 징역 7년",https://www.yna.co.kr/view/AKR2022062409550005...
23,23,2022.06.24.,'다음엔 좋은 부모 만나' 지적장애 딸 살해한 엄마…징역 6년,https://news.jtbc.joins.com/article/article.as...
24,24,2022.06.21.,"""4천만원 갚아!"" 사촌형수 살해, 국민참여재판 징역20년",http://www.newsis.com/view/?id=NISX20220620_00...
25,25,2022.06.21.,편의점 직원 살해한 40대 무기징역 구형,https://news.kbs.co.kr/news/view.do?ncd=549153...
26,26,2022.06.22.,"검찰, ‘막대기 살해’ 스포츠센터 대표 징역 25년에 항소",https://www.donga.com/news/article/all/2022062...
27,27,2022.06.23.,음주운전 사고 피해자 살해하려한 50대 징역형,https://www.news1.kr/articles/?4720996
28,28,2022.06.16.,"'前여친 보복살해' 김병찬 1심 징역 35년…""살해 계획한 것""",http://www.newsis.com/view/?id=NISX20220616_00...
29,29,2022.06.21.,"'신변보호 여성母 살해' 이석준, 1심 무기징역…""사회 격리 필요""",http://www.newsis.com/view/?id=NISX20220621_00...

In [94]:
news_df_6.drop_duplicates(['title'])

,Unnamed: 0,date,title,url
0,0,2022.06.30.,"'자녀 살해한 부모' 처벌 강화법, 국회 발의돼 있지만…",https://news.jtbc.joins.com/article/article.as...
1,1,2022.06.30.,"자녀살해 후 극단선택…법원은 ""동반자살 아닌 살인"" 질타",https://www.yna.co.kr/view/AKR2022063008310000...
2,2,2022.06.30.,"독일 법원, 혐의 부인한 101세 나치 부역자에 '징역 5년' 선고",http://news.mt.co.kr/mtview.php?no=20220630084...
3,3,2022.06.30.,"자녀 동반 비극은 '비속살해'…""자녀 생명은 부모의 것 아냐""",http://www.newsis.com/view/?id=NISX20220630_00...
4,4,2022.06.29.,"‘중년여성·공범 살해’ 권재찬, 1심 사형 불복해 항소… 검찰도 맞항소",https://www.seoul.co.kr/news/newsView.php?id=2...
...,...,...,...,...
95,95,2022.06.16.,'70㎝ 막대기'로 찔러 죽였다…엽기살인범 1심서 징역 25년,https://www.joongang.co.kr/article/25079618
96,96,2022.06.24.,"'연인에게 딴 남자가…' 상대男 살인미수 20대, 2심도 징역3년",http://news.mt.co.kr/mtview.php?no=20220624145...
97,97,2022.06.22.,‘신변보호女 母 살해’ 이석준에 주소 유출한 공무원 전국민 개인정보 볼 수 있었다…...,http://www.segye.com/content/html/2022/06/22/2...
98,98,2022.06.10.,2세 아동 개사료 먹게 만든 학대살해 부모 무기징역 구형,http://www.fnnews.com/news/202206101308579951
99,99,2022.06.17.,"'생활고' 속 장애아들 살해 40대 母, 징역 4년",https://www.nocutnews.co.kr/news/5773330