### News Crawling

In [30]:
# 네이버 뉴스 여성 살해 검거 검색 >> 2022/1월

# 라이브러리
import requests
from bs4 import BeautifulSoup 
import urllib
import urllib.request as rq
import pandas as pd
import requests
import openpyxl
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
import re
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager


# 웹드라이버 설정
options = webdriver.ChromeOptions()
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option("useAutomationExtension", False)



start=1
news_df = pd.DataFrame()

while True:
    try:
        url = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query=%EC%97%AC%EC%84%B1%20%EC%82%B4%ED%95%B4%20%EA%B2%80%EA%B1%B0&sort=0&photo=0&field=0&pd=3&ds=2022.01.01&de=2022.01.31&cluster_rank=53&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20220101to20220131,a:all&start=1'.format(start)

        # url = https://search.naver.com/search.naver?where=news&sm=tab_jum&query='+keyword+'&start='+str(page_num)
        #url = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query='+keyword+'&sort=1&photo=0&field=0&pd=3&ds='+date_s+'&de='+date_e+'&start='+str(page)
        headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'}


        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'lxml')

        news_title = [title['title'] for title in soup.find_all('a', attrs={'class':'news_tit'})]
        news_url = [url['href'] for url in soup.find_all('a',attrs={'class':'news_tit'})]
        dates = [date.get_text() for date in soup.find_all('span', attrs={'class':'info'})]
       
        news_date = []
        for date in dates:
            if re.search(r'\d+.\d+.\d+',date) !=None:
                news_date.append(date)

        new_df = set(news_title)        

        df = pd.DataFrame({'date':news_date,'title':news_title, 'url':news_url})
        news_df  = pd.concat([news_df, df], ignore_index=True)
        start += 10

    except:
        print(start)
        break

4591

In [31]:
news_df_1 = news_df.copy()
news_df_1.to_csv('news_df_1.csv')
news_df_1 = pd.read_csv('news_df_1.csv')
news_df_1

,Unnamed: 0,date,title,url
0,0,2022.01.29.,'악의 마음' 김남길X진선규 어쩌나..연쇄살인범 검거 난항 [★밤TView],http://star.mt.co.kr/stview.php?no=20220129214...
1,1,2022.01.27.,차 타는 순간 흉기로 여성 위협…금품 빼앗은 강도 검거,http://www.edaily.co.kr/news/newspath.asp?news...
2,2,2022.01.25.,차량서 50대 여성 흉기에 찔려 숨진 채 발견…남편 살해 추정,https://www.news1.kr/articles/?4565509
3,3,2022.01.19.,이별 통보한 전 여친 살해한 27세 조현진 신상공개,http://news.kmib.co.kr/article/view.asp?arcid=...
4,4,2022.01.29.,'악의 마음' 부유층 연쇄살인 발생에 유영철 재조명 '10개월 간 20명 살해',http://www.gukjenews.com/news/articleView.html...
...,...,...,...,...
4585,4585,2022.01.28.,"경찰, 이별 통보에 '흉기 사진' 보낸 40대 불법 체류자 검거",https://www.ytn.co.kr/_ln/0103_202201281526301793
4586,4586,2022.01.13.,이별 통보한 여성에게 흉기 휘둘러 살해한 20대 검거,http://yna.kr/AKR20220113024800063?did=1195m
4587,4587,2022.01.10.,‘신변보호’ 피해자 주소 살해범에 넘긴 정보원은 구청 공무원,https://www.seoul.co.kr/news/newsView.php?id=2...
4588,4588,2022.01.13.,천안 원룸서 여자친구 살해 혐의 20대 남성 검거,https://news.kbs.co.kr/news/view.do?ncd=537214...
4589,4589,2022.01.13.,"""헤어지자""‥전 여자친구 살해한 20대 검거",https://imnews.imbc.com/replay/2022/nwdesk/art...

In [32]:
news_df_1.drop_duplicates(['title'])

,Unnamed: 0,date,title,url
0,0,2022.01.29.,'악의 마음' 김남길X진선규 어쩌나..연쇄살인범 검거 난항 [★밤TView],http://star.mt.co.kr/stview.php?no=20220129214...
1,1,2022.01.27.,차 타는 순간 흉기로 여성 위협…금품 빼앗은 강도 검거,http://www.edaily.co.kr/news/newspath.asp?news...
2,2,2022.01.25.,차량서 50대 여성 흉기에 찔려 숨진 채 발견…남편 살해 추정,https://www.news1.kr/articles/?4565509
3,3,2022.01.19.,이별 통보한 전 여친 살해한 27세 조현진 신상공개,http://news.kmib.co.kr/article/view.asp?arcid=...
4,4,2022.01.29.,'악의 마음' 부유층 연쇄살인 발생에 유영철 재조명 '10개월 간 20명 살해',http://www.gukjenews.com/news/articleView.html...
5,5,2022.01.28.,"경찰, 이별 통보에 '흉기 사진' 보낸 40대 불법 체류자 검거",https://www.ytn.co.kr/_ln/0103_202201281526301793
6,6,2022.01.13.,이별 통보한 여성에게 흉기 휘둘러 살해한 20대 검거,http://yna.kr/AKR20220113024800063?did=1195m
7,7,2022.01.10.,‘신변보호’ 피해자 주소 살해범에 넘긴 정보원은 구청 공무원,https://www.seoul.co.kr/news/newsView.php?id=2...
8,8,2022.01.13.,천안 원룸서 여자친구 살해 혐의 20대 남성 검거,https://news.kbs.co.kr/news/view.do?ncd=537214...
9,9,2022.01.13.,"""헤어지자""‥전 여자친구 살해한 20대 검거",https://imnews.imbc.com/replay/2022/nwdesk/art...

In [33]:
# 네이버 뉴스 여성 살해 검거 검색 >> 2022/2월

# 라이브러리
import requests
from bs4 import BeautifulSoup 
import urllib
import urllib.request as rq
import pandas as pd
import requests
import openpyxl
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
import re
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager


# 웹드라이버 설정
options = webdriver.ChromeOptions()
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option("useAutomationExtension", False)



start=1
news_df = pd.DataFrame()

while True:
    try:
        url = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query=%EC%97%AC%EC%84%B1%20%EC%82%B4%ED%95%B4%20%EA%B2%80%EA%B1%B0&sort=0&photo=0&field=0&pd=3&ds=2022.02.01&de=2022.02.28&cluster_rank=82&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20220201to20220228,a:all&start=1'.format(start)
        headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'}

        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'lxml')

        news_title = [title['title'] for title in soup.find_all('a', attrs={'class':'news_tit'})]
        news_url = [url['href'] for url in soup.find_all('a',attrs={'class':'news_tit'})]
        dates = [date.get_text() for date in soup.find_all('span', attrs={'class':'info'})]
       
        news_date = []
        for date in dates:
            if re.search(r'\d+.\d+.\d+',date) !=None:
                news_date.append(date)

        new_df = set(news_title)        

        df = pd.DataFrame({'date':news_date,'title':news_title, 'url':news_url})
        news_df  = pd.concat([news_df, df], ignore_index=True)
        start += 10

    except:
        print(start)
        break

1961

In [34]:
news_df_2 = news_df.copy()
news_df_2.to_csv('news_df_2.csv')
news_df_2 = pd.read_csv('news_df_2.csv')
news_df_2

,Unnamed: 0,date,title,url
0,0,2022.02.26.,"'악의 마음', 부유층 연쇄살인범 검거→도주..'충격 엔딩' [종합]",http://star.mt.co.kr/stview.php?no=20220226065...
1,1,2022.02.26.,'동거녀 살해·평소 알고 지낸 여성 흉기' 찌른 50대 중국인 검거,http://www.kyeongin.com/main/view.php?key=2022...
2,2,2022.02.26.,"""찌질한 살인자일 뿐""...'악의 마음' 김남길, 연쇄살인범 검거 [종합]",https://www.xportsnews.com/article/1542193
3,3,2022.02.23.,안양서 식당 주인 살해 뒤 대전까지 도주…40대 남성 체포,https://news.kbs.co.kr/news/view.do?ncd=540243...
4,4,2022.02.25.,"김제에서 50대 여성 숨진 채 발견.. ""살해 용의자 검거""",http://www.jmbc.co.kr/news/view/22009
...,...,...,...,...
1955,1955,2022.02.15.,"서울서 또 신변보호 여성 피살…경찰, 용의자 추적 중",https://www.news1.kr/articles/?4584803
1956,1956,2022.02.15.,[단독]또 신변보호 여성 사망···스마트워치로 경찰에 알렸지만 못 막았다,https://www.khan.co.kr/national/national-gener...
1957,1957,2022.02.15.,[속보] 구로 신변보호 대상 여성 살해 용의자 숨진채 발견,http://news.mk.co.kr/newsRead.php?no=140990&ye...
1958,1958,2022.02.11.,"""나를 무시해 홧김에""…60대 부인 살해한 남편 검거(종합)",http://www.newsis.com/view/?id=NISX20220211_00...
1959,1959,2022.02.24.,안양서 70대 업주 살해 후 도주한 40대男 사흘 만에 검거,http://www.hg-times.com/news/articleView.html?...

In [8]:
# 네이버 뉴스 여성 살해 검거 검색 >> 2022/3월

# 라이브러리
import requests
from bs4 import BeautifulSoup 
import urllib
import urllib.request as rq
import pandas as pd
import requests
import openpyxl
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
import re
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager


# 웹드라이버 설정
options = webdriver.ChromeOptions()
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option("useAutomationExtension", False)



start=1
news_df = pd.DataFrame()

while True:
    try:
        url = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query=%EC%97%AC%EC%84%B1%20%EC%82%B4%ED%95%B4%20%EA%B2%80%EA%B1%B0&sort=0&photo=0&field=0&pd=3&ds=2022.03.01&de=2022.03.31&cluster_rank=25&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20220301to20220331,a:all&start=1'.format(start)

        # url = https://search.naver.com/search.naver?where=news&sm=tab_jum&query='+keyword+'&start='+str(page_num)
        #url = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query='+keyword+'&sort=1&photo=0&field=0&pd=3&ds='+date_s+'&de='+date_e+'&start='+str(page)
        headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'}


        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'lxml')

        news_title = [title['title'] for title in soup.find_all('a', attrs={'class':'news_tit'})]
        news_url = [url['href'] for url in soup.find_all('a',attrs={'class':'news_tit'})]
        dates = [date.get_text() for date in soup.find_all('span', attrs={'class':'info'})]
       
        news_date = []
        for date in dates:
            if re.search(r'\d+.\d+.\d+',date) !=None:
                news_date.append(date)

        new_df = set(news_title)        

        df = pd.DataFrame({'date':news_date,'title':news_title, 'url':news_url})
        news_df  = pd.concat([news_df, df], ignore_index=True)
        start += 10

    except:
        print(start)
        break

3311

In [9]:
news_df_3 = news_df.copy()
news_df_3.to_csv('news_df_3.csv')
news_df_3 = pd.read_csv('news_df_3.csv')
news_df_3

,Unnamed: 0,date,title,url
0,0,2022.03.30.,수영 못하는 남편 다이빙시켜 살해…아내·공범 공개수배,http://news.kmib.co.kr/article/view.asp?arcid=...
1,1,2022.03.30.,‘가평 계곡 살인’ 30대 여성·공범 공개수배,http://www.segye.com/content/html/2022/03/30/2...
2,2,2022.03.24.,'신변보호 여성 가족살해' 이석준에 정보 판 30대 징역 2년 구형,http://news.tf.co.kr/read/life/1926550.htm
3,3,2022.03.25.,이웃 성폭행하고 살해…인면수심 40대 징역 30년,https://www.nocutnews.co.kr/news/5729202
4,4,2022.03.25.,이웃집 60대 여성 성폭행·살해한 40대 남성 징역 30년,https://biz.chosun.com/topics/law_firm/2022/03...
...,...,...,...,...
3305,3305,2022.03.28.,"“스토킹 살해범 김병찬, 사형 처해달라”…재판부 향한 유족들의 절규",http://www.segye.com/content/html/2022/03/28/2...
3306,3306,2022.03.13.,호신용품으로 동거남 때려 살해한 30대 여성 검거,http://yna.kr/AKR20220313016000064?did=1195m
3307,3307,2022.03.17.,"""집수리 왜 안 해줘""..집주인 살해한 60대, 긴급체포",http://www.fnnews.com/news/202203171031508306
3308,3308,2022.03.26.,‘돈 빌려달라’ 거절한 이웃집 여성 성폭행 후 살해한 40대…피해자인양 휴대폰 안부...,http://www.segye.com/content/html/2022/03/25/2...
3309,3309,2022.03.16.,"“한국의 여성운동, ‘피해망상 페미니즘’으로 변질됐다”",https://www.chosun.com/national/national_gener...

In [10]:
# 네이버 뉴스 여성 살해 검거 검색 >> 2022/4월

# 라이브러리
import requests
from bs4 import BeautifulSoup 
import urllib
import urllib.request as rq
import pandas as pd
import requests
import openpyxl
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
import re
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager


# 웹드라이버 설정
options = webdriver.ChromeOptions()
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option("useAutomationExtension", False)



start=1
news_df = pd.DataFrame()

while True:
    try:
        url = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query=%EC%97%AC%EC%84%B1%20%EC%82%B4%ED%95%B4%20%EA%B2%80%EA%B1%B0&sort=0&photo=0&field=0&pd=3&ds=2022.04.01&de=2022.04.30&cluster_rank=44&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20220401to20220430,a:all&start=1'.format(start)
        headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'}


        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'lxml')

        news_title = [title['title'] for title in soup.find_all('a', attrs={'class':'news_tit'})]
        news_url = [url['href'] for url in soup.find_all('a',attrs={'class':'news_tit'})]
        dates = [date.get_text() for date in soup.find_all('span', attrs={'class':'info'})]
       
        news_date = []
        for date in dates:
            if re.search(r'\d+.\d+.\d+',date) !=None:
                news_date.append(date)

        new_df = set(news_title)        

        df = pd.DataFrame({'date':news_date,'title':news_title, 'url':news_url})
        news_df  = pd.concat([news_df, df], ignore_index=True)
        start += 10

    except:
        print(start)
        break

3301

In [11]:
news_df_4 = news_df.copy()
news_df_4.to_csv('news_df_4.csv')
news_df_4 = pd.read_csv('news_df_4.csv')
news_df_4

,Unnamed: 0,date,title,url
0,0,2022.04.25.,강서구 60대 여성 살해 피의자 검거… “돈 많을 줄 알았다”,http://www.segye.com/content/html/2022/04/25/2...
1,1,2022.04.27.,"""돈 많아 보여서"" 이웃 살해 40대…1시간 구속심사(종합)",http://www.newsis.com/view/?id=NISX20220427_00...
2,2,2022.04.25.,강서구 아파트 60대 여성 살해 40대 남성 검거…“돈 필요해서”,https://www.hani.co.kr/arti/society/society_ge...
3,3,2022.04.26.,"경찰, 강서구 60대 여성 살해 40대 남성 구속영장 신청",http://www.fnnews.com/news/202204261120167268
4,4,2022.04.27.,"'강서구 이웃 여성 살인' 피의자 구속…""도망 염려""",https://www.nocutnews.co.kr/news/5747828
...,...,...,...,...
3295,3295,2022.04.27.,강서 60대 여성 살해 40대 이웃 남성 구속,https://www.news1.kr/articles/?4663183
3296,3296,2022.04.24.,"경찰, 서울 강서구 60대女 살해 용의자 40대男 추적",https://www.donga.com/news/article/all/2022042...
3297,3297,2022.04.25.,등촌동 여성 살해 용의자 검거…“단 몇 만원 때문에”?,https://news.kbs.co.kr/news/view.do?ncd=544833...
3298,3298,2022.04.27.,이웃집 60대女 살해 뒤…장롱 서랍 속 2만원 갖고 튄 그놈,https://www.joongang.co.kr/article/25066932
3299,3299,2022.04.25.,[속보] 서울 등촌동 아파트 강도살인 피의자 검거...40대 이웃 남성,https://www.ytn.co.kr/_ln/0103_202204250851476837

In [13]:
# 네이버 뉴스 여성 살해 검거 검색 >> 2022/5월

# 라이브러리
import requests
from bs4 import BeautifulSoup 
import urllib
import urllib.request as rq
import pandas as pd
import requests
import openpyxl
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
import re
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager


# 웹드라이버 설정
options = webdriver.ChromeOptions()
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option("useAutomationExtension", False)



start=1
news_df = pd.DataFrame()

while True:
    try:
        url = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query=%EC%97%AC%EC%84%B1%20%EC%82%B4%ED%95%B4%20%EA%B2%80%EA%B1%B0&sort=0&photo=0&field=0&pd=3&ds=2022.05.01&de=2022.05.31&cluster_rank=41&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20220501to20220531,a:all&start=1'.format(start)
        headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'}


        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'lxml')

        news_title = [title['title'] for title in soup.find_all('a', attrs={'class':'news_tit'})]
        news_url = [url['href'] for url in soup.find_all('a',attrs={'class':'news_tit'})]
        dates = [date.get_text() for date in soup.find_all('span', attrs={'class':'info'})]
       
        news_date = []
        for date in dates:
            if re.search(r'\d+.\d+.\d+',date) !=None:
                news_date.append(date)

        new_df = set(news_title)        

        df = pd.DataFrame({'date':news_date,'title':news_title, 'url':news_url})
        news_df  = pd.concat([news_df, df], ignore_index=True)
        start += 10

    except:
        print(start)
        break

3361

In [14]:
news_df_5 = news_df.copy()
news_df_5.to_csv('news_df_5.csv')
news_df_5 = pd.read_csv('news_df_5.csv')
news_df_5

,Unnamed: 0,date,title,url
0,0,2022.05.27.,전 남편 차로 치어 살해하려 한 여성 검거‥공무집행 방해도,https://imnews.imbc.com/news/2022/society/arti...
1,1,2022.05.24.,중증장애 딸 살해 후 극단 선택 시도한 60대 여성 검거,https://news.sbs.co.kr/news/endPage.do?news_id...
2,2,2022.05.24.,"""30년간 홀로 돌봄""...중증장애 딸 살해한 60대 검거",https://www.ytn.co.kr/_ln/0103_202205241246390721
3,3,2022.05.24.,'뇌병변 장애 앓는 딸' 수면제 먹여 살해한 60대 친모 검거,http://www.newsis.com/view/?id=NISX20220524_00...
4,4,2022.05.26.,"""너무 미안해"" 30년간 뇌병변 딸 돌보다 살해한 엄마 영장 기각",http://www.fnnews.com/news/202205252249229863
...,...,...,...,...
3355,3355,2022.05.23.,인천시 남동구 빌라서 여성 살해한 20대 남성 검거,https://news.kbs.co.kr/news/view.do?ncd=546946...
3356,3356,2022.05.25.,"""같이 살지 못해 미안해""… 뇌병변 딸 살해한 친모, 영장심사",http://moneys.mt.co.kr/news/mwView.php?no=2022...
3357,3357,2022.05.25.,동거남 살해한 혐의 50대 여성 검거… 경찰 “술 마시다 다툰 듯”,http://www.segye.com/content/html/2022/05/25/2...
3358,3358,2022.05.16.,부산 해운대 주택서 50대 여성 살해한 60대 남성 검거(종합),https://www.yna.co.kr/view/AKR2022051600540105...
3359,3359,2022.05.24.,지적장애인 인천·김포서 살해·암매장 2030 남녀 4명 구속기소,https://news.imaeil.com/page/view/202205241931...

In [15]:
# 네이버 뉴스 여성 살해 검거 검색 >> 2022/6월

# 라이브러리
import requests
from bs4 import BeautifulSoup 
import urllib
import urllib.request as rq
import pandas as pd
import requests
import openpyxl
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
import re
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager


# 웹드라이버 설정
options = webdriver.ChromeOptions()
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option("useAutomationExtension", False)



start=1
news_df = pd.DataFrame()

while True:
    try:
        url = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query=%EC%97%AC%EC%84%B1%20%EC%82%B4%ED%95%B4%20%EA%B2%80%EA%B1%B0&sort=0&photo=0&field=0&pd=3&ds=2022.06.01&de=2022.06.30&cluster_rank=47&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20220601to20220630,a:all&start=1'.format(start)
        headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'}


        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'lxml')

        news_title = [title['title'] for title in soup.find_all('a', attrs={'class':'news_tit'})]
        news_url = [url['href'] for url in soup.find_all('a',attrs={'class':'news_tit'})]
        dates = [date.get_text() for date in soup.find_all('span', attrs={'class':'info'})]
       
        news_date = []
        for date in dates:
            if re.search(r'\d+.\d+.\d+',date) !=None:
                news_date.append(date)

        new_df = set(news_title)        

        df = pd.DataFrame({'date':news_date,'title':news_title, 'url':news_url})
        news_df  = pd.concat([news_df, df], ignore_index=True)
        start += 10

    except:
        print(start)
        break

2861

In [16]:
news_df_6 = news_df.copy()
news_df_6.to_csv('news_df_6.csv')
news_df_6 = pd.read_csv('news_df_6.csv')
news_df_6

,Unnamed: 0,date,title,url
0,0,2022.06.22.,청주 40대 여성 살해 용의자 사흘 만에 검거,https://www.yna.co.kr/view/AKR2022062215830006...
1,1,2022.06.17.,부산서 귀가 중인 여성 흉기 살해 60대 검거,http://www.newsis.com/view/?id=NISX20220617_00...
2,2,2022.06.22.,'이사 비용 때문에'… 이웃 여성 살해하고 금품 훔친 40대,http://www.segye.com/content/html/2022/06/22/2...
3,3,2022.06.10.,강남 자택서 40대 남편 흉기 살해한 20대 여성 검거,http://www.fnnews.com/news/202206101035343624
4,4,2022.06.22.,청주 40대 여성 살인사건 용의자 사흘 만에 수원서 검거,http://www.edaily.co.kr/news/newspath.asp?news...
...,...,...,...,...
2855,2855,2022.06.22.,80대 노모와 다투다 흉기 휘두른 아들 검거,http://mbn.mk.co.kr/pages/news/newsView.php?ca...
2856,2856,2022.06.19.,"정신질환 남성, 지적장애 여성과 동거…한달만에 ""사탄인줄"" 살해",http://news.mt.co.kr/mtview.php?no=20220619200...
2857,2857,2022.06.25.,'1심 사형 선고' 권재찬 어떻게 살았나… 유년시절부터 강도살해까지 보니,https://www.news1.kr/articles/?4722502
2858,2858,2022.06.17.,부산서 지인 여성 살해 뒤 도주했던 60대 남성 검거,https://www.seoul.co.kr/news/newsView.php?id=2...
2859,2859,2022.06.23.,"청주 40대 여성 살해 용의자, 범행 모두 인정",https://www.cjb.co.kr/home/sub.php?menukey=61&...

In [18]:
news_df_5

,Unnamed: 0,date,title,url
0,0,2022.05.27.,전 남편 차로 치어 살해하려 한 여성 검거‥공무집행 방해도,https://imnews.imbc.com/news/2022/society/arti...
1,1,2022.05.24.,중증장애 딸 살해 후 극단 선택 시도한 60대 여성 검거,https://news.sbs.co.kr/news/endPage.do?news_id...
2,2,2022.05.24.,"""30년간 홀로 돌봄""...중증장애 딸 살해한 60대 검거",https://www.ytn.co.kr/_ln/0103_202205241246390721
3,3,2022.05.24.,'뇌병변 장애 앓는 딸' 수면제 먹여 살해한 60대 친모 검거,http://www.newsis.com/view/?id=NISX20220524_00...
4,4,2022.05.26.,"""너무 미안해"" 30년간 뇌병변 딸 돌보다 살해한 엄마 영장 기각",http://www.fnnews.com/news/202205252249229863
...,...,...,...,...
3355,3355,2022.05.23.,인천시 남동구 빌라서 여성 살해한 20대 남성 검거,https://news.kbs.co.kr/news/view.do?ncd=546946...
3356,3356,2022.05.25.,"""같이 살지 못해 미안해""… 뇌병변 딸 살해한 친모, 영장심사",http://moneys.mt.co.kr/news/mwView.php?no=2022...
3357,3357,2022.05.25.,동거남 살해한 혐의 50대 여성 검거… 경찰 “술 마시다 다툰 듯”,http://www.segye.com/content/html/2022/05/25/2...
3358,3358,2022.05.16.,부산 해운대 주택서 50대 여성 살해한 60대 남성 검거(종합),https://www.yna.co.kr/view/AKR2022051600540105...
3359,3359,2022.05.24.,지적장애인 인천·김포서 살해·암매장 2030 남녀 4명 구속기소,https://news.imaeil.com/page/view/202205241931...

In [22]:
news_df_5.drop_duplicates(['title','url'])

,Unnamed: 0,date,title,url
0,0,2022.05.27.,전 남편 차로 치어 살해하려 한 여성 검거‥공무집행 방해도,https://imnews.imbc.com/news/2022/society/arti...
1,1,2022.05.24.,중증장애 딸 살해 후 극단 선택 시도한 60대 여성 검거,https://news.sbs.co.kr/news/endPage.do?news_id...
2,2,2022.05.24.,"""30년간 홀로 돌봄""...중증장애 딸 살해한 60대 검거",https://www.ytn.co.kr/_ln/0103_202205241246390721
3,3,2022.05.24.,'뇌병변 장애 앓는 딸' 수면제 먹여 살해한 60대 친모 검거,http://www.newsis.com/view/?id=NISX20220524_00...
4,4,2022.05.26.,"""너무 미안해"" 30년간 뇌병변 딸 돌보다 살해한 엄마 영장 기각",http://www.fnnews.com/news/202205252249229863
5,5,2022.05.23.,인천시 남동구 빌라서 여성 살해한 20대 남성 검거,https://news.kbs.co.kr/news/view.do?ncd=546946...
6,6,2022.05.25.,"""같이 살지 못해 미안해""… 뇌병변 딸 살해한 친모, 영장심사",http://moneys.mt.co.kr/news/mwView.php?no=2022...
7,7,2022.05.25.,동거남 살해한 혐의 50대 여성 검거… 경찰 “술 마시다 다툰 듯”,http://www.segye.com/content/html/2022/05/25/2...
8,8,2022.05.16.,부산 해운대 주택서 50대 여성 살해한 60대 남성 검거(종합),https://www.yna.co.kr/view/AKR2022051600540105...
9,9,2022.05.24.,지적장애인 인천·김포서 살해·암매장 2030 남녀 4명 구속기소,https://news.imaeil.com/page/view/202205241931...